/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifrn.sigcopein.view;

import javax.swing.JInternalFrame;

/**
 *
 * @author 1935921
 */
public class Principal extends javax.swing.JFrame {

    private JInternalFrame internal;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnServidores = new javax.swing.JMenuItem();
        mnAlunos = new javax.swing.JMenuItem();
        mnEdital = new javax.swing.JMenuItem();
        mnBanco = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdPrincipalLayout = new javax.swing.GroupLayout(jdPrincipal);
        jdPrincipal.setLayout(jdPrincipalLayout);
        jdPrincipalLayout.setHorizontalGroup(
            jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 976, Short.MAX_VALUE)
        );
        jdPrincipalLayout.setVerticalGroup(
            jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Sair");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastro");

        mnServidores.setText("Servidores");
        mnServidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnServidoresActionPerformed(evt);
            }
        });
        jMenu2.add(mnServidores);

        mnAlunos.setText("Alunos");
        mnAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlunosActionPerformed(evt);
            }
        });
        jMenu2.add(mnAlunos);

        mnEdital.setText("Edital");
        mnEdital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEditalActionPerformed(evt);
            }
        });
        jMenu2.add(mnEdital);

        mnBanco.setText("Banco");
        mnBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBancoActionPerformed(evt);
            }
        });
        jMenu2.add(mnBanco);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Projetos");

        jMenuItem3.setText("Gerenciar Projetos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Gerenciar Alunos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Gerenciar Servidores");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnServidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnServidoresActionPerformed
        // TODO add your handling code here:
        ViewListaServidores view = new ViewListaServidores(this);
        view.setVisible(true);
        AddInternalFrame(view);
    }//GEN-LAST:event_mnServidoresActionPerformed

    private void mnAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlunosActionPerformed
        // TODO add your handling code here:
        ViewListaAlunos view = new ViewListaAlunos(this);
        view.setVisible(true);
        AddInternalFrame(view);
    }//GEN-LAST:event_mnAlunosActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:

        ViewListaProjetos view = new ViewListaProjetos(this);
        view.setVisible(true);
        AddInternalFrame(view);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        ViewListaAlunosProjetos view = new ViewListaAlunosProjetos(this);
        view.setVisible(true);
        AddInternalFrame(view);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mnEditalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEditalActionPerformed
        // TODO add your handling code here:
        ViewListaEdital view = new ViewListaEdital(this);
        view.setVisible(true);
        AddInternalFrame(view);
    }//GEN-LAST:event_mnEditalActionPerformed

    private void mnBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBancoActionPerformed
        // TODO add your handling code here:
        ViewListaBanco view = new ViewListaBanco(this);
        view.setVisible(true);
        AddInternalFrame(view);
    }//GEN-LAST:event_mnBancoActionPerformed

    private void AddInternalFrame(JInternalFrame j) {
        jdPrincipal.add(j);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JDesktopPane jdPrincipal;
    private javax.swing.JMenuItem mnAlunos;
    private javax.swing.JMenuItem mnBanco;
    private javax.swing.JMenuItem mnEdital;
    private javax.swing.JMenuItem mnServidores;
    // End of variables declaration//GEN-END:variables
}
